version: '3.8'

services:
  db:
    image: postgres:13
    env_file: 
      - .env  # Load environment variables from the .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend  # Point to the Dockerfile in the backend directory
    command: python manage.py runserver 0.0.0.0:8000
    env_file: 
      - .env  # Load the same .env file for Django if needed
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
