# Generated by Django 4.2.16 on 2024-11-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medication',
            name='refill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='reminder_times',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='medication',
            name='repeat_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
