# Generated by Django 4.2.16 on 2024-11-15 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allergy_tracker', '0002_remove_medication_reminder_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='last_taken',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='repeat_count',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='start_date',
        ),
        migrations.AddField(
            model_name='medication',
            name='refill_notification_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='reminder_notification_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
