# Generated by Django 4.2.16 on 2024-11-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_tracker', '0004_alter_symptomtracking_topallergens'),
        ('allergy_tracker', '0004_medication_end_date_medication_start_date'),
    ]

    operations = [
    ]
