# Generated by Django 4.2.16 on 2024-11-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_tracker', '0005_merge_20241115_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
