# Generated by Django 4.2.16 on 2024-11-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_tracker', '0007_alter_devicetoken_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pollen_sensitivity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='symptom_tracking_enabled',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Toronto', max_length=255),
            preserve_default=False,
        ),
    ]
