# Generated by Django 4.2.16 on 2024-11-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_tracker', '0008_remove_userprofile_pollen_sensitivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Unknown City', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
    ]
