# Generated by Django 4.2.16 on 2024-11-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_tracker', '0009_alter_userprofile_city_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
